platform: linux

inputs:
- name: pcf-automation-source
- name: config # contains the director ssl configuration file
- name: env # contains the env file with target OpsMan Information

params:
  ENV_FILE: env.yml
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input
  CERTIFICATE_PEM: ops_manager_fullchain.pem
  PRIVATE_KEY_PEM: ops_manager_privkey.pem

run:
  path: pcf-automation-source/tasks/configure-director-ssl.sh