---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: voor/dehydrated-route53
    tag: latest
inputs:
  - name: pcf-automation-source
  - name: certificates
  - name: certificates-version
outputs:
  - name: updated-certificates
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  ENV_NAME:
  DNS_SUFFIX:
  CURL_OPTS:
  CA:
run:
  path: pcf-automation-source/tasks/dehydrated.sh