## This file is leveraged after creating the system cluster to expose the necessary certificates to whatever ingress tool is used inside the cluster.

apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: v1
kind: Secret
metadata:
  name: default-ssl-certificate
  namespace: ingress
type: kubernetes.io/tls
data:
  tls.crt: {{ include "fullchain" | default "" | b64enc | quote }}
  tls.key: {{ include "privkey" | default "" | b64enc | quote }}